title: Landon Vong
text: Hello, my name is Landon Vong. I am majoring in Software Development at the University of Utah. My hobbies include golfing and being with my dogs Ari and Emi.
theme: jekyll-theme-minimal
